# Generated by Django 5.2.9 on 2025-12-19 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostMascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField()),
                ("foto", models.ImageField(upload_to="posts_mascotas/")),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="app1.mascota",
                    ),
                ),
            ],
        ),
    ]
